services:
  api:
    restart: unless-stopped
    image: ghcr.io/${GHCR_OWNER:-taskflow}/taskflow-api:${IMAGE_TAG:-local}

  worker:
    restart: unless-stopped
    image: ghcr.io/${GHCR_OWNER:-taskflow}/taskflow-worker:${IMAGE_TAG:-local}

  frontend:
    restart: unless-stopped
    image: ghcr.io/${GHCR_OWNER:-taskflow}/taskflow-frontend:${IMAGE_TAG:-local}

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      api:
        condition: service_healthy
      frontend:
        condition: service_healthy
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
